language: php

script:
  - ./bin/phpunit 

matrix:
  include:
   - php: 7.1
     env: PHPUNIT_VERSION=6.5.14
     dist: trusty

   - php: 7.1
     env: PHPUNIT_VERSION=7.5
     dist: trusty

   - php: 7.2
     env: PHPUNIT_VERSION=6.5.14
     dist: trusty

   - php: 7.2
     env: PHPUNIT_VERSION=7.5
     dist: trusty

   - php: 7.2
     env: PHPUNIT_VERSION=8.1
     dist: trusty

   - php: 7.3
     env: PHPUNIT_VERSION=7.5
     dist: trusty

   - php: 7.3
     env: PHPUNIT_VERSION=8.1
     dist: trusty

   - php: 7.3
     env: PHPUNIT_VERSION=9.0
     dist: trusty

   - php: 7.3
     env: PHPUNIT_VERSION=9.5
     dist: xenial

   - php: 7.4
     env: PHPUNIT_VERSION=8.5
     dist: xenial

   - php: 7.4
     env: PHPUNIT_VERSION=9.0
     dist: xenial

   - php: 7.4
     env: PHPUNIT_VERSION=9.5
     dist: xenial

install:
  - composer require --dev phpunit/phpunit:${PHPUNIT_VERSION}
  - composer install --dev

jobs:
  include:
    - stage: Coverage
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ./bin/phpunit --coverage-clover=build/logs/clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
